refactor : Replace fx-layout with tailwind equivalent - discussion-prompt-composer
thoth-tech/doubtfire-web pull request #125
Opened 2023-12-03 12:23 UTC by Hashmi125

# Description

Key points to note:

- I replaced fxLayout and fxLayoutAlign with Tailwind CSS utility classes for flexible layout.
- Applied Tailwind CSS classes for text alignment and margin.
- Used *ngFor for better readability in the loop.
- Added a Tailwind CSS divider (my-12 for vertical margin) for visual separation.

## Testing Checklist:

- [x] Tested in latest Chrome
- [x] Tested in latest Safari
- [x] Tested in latest Firefox

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have requested a review from @macite and @jakerenzella on the Pull Request

Before Output :

![x](https://github.com/thoth-tech/doubtfire-web/assets/118825420/38af789b-0f40-4a97-b02b-55b4021e0e01)

After Output : 

![xx](https://github.com/thoth-tech/doubtfire-web/assets/118825420/28f9a88b-2b09-46c0-8712-9e5c38ed1afc)

2023-12-11 18:44 UTC, maddernd commented
@Hashmi125 who is reviewing this, you need to arrange with another student to review your work asap.

2023-12-13 03:36 UTC, BrianJCal99 requested changes
All fxLayout components have been successfully replaced with Tailwind CSS equivalents. Before and after screenshots are identical. 

Minor issues need to be fixed:

1. Remove Tailwind Import in line #1. It is already in the codebase, and no need to import it again.
2. Undo the changes in lines #15 and #51
3. Undo all the changes you have done to components from the Angular Material library. (mat and ng)
4. Fix format by running prettier extension on the file.

2023-12-16 08:08 UTC, AusBruce commented
I've reviewed the changes where fxLayout was replaced with Tailwind CSS classes.
It's great to see that the refactoring has been done.
I tested the branch locally and didn't encounter any errors.
The 'Before and After' comparisons also confirm that the visual aspects remain unchanged. @Hashmi125

2024-04-29 02:04 UTC, maddernd commented
please make this one upstream after updating it.

2024-04-29 02:04 UTC, closed without merging