Migrate/analytics2
thoth-tech/doubtfire-web pull request #256
Opened 2024-09-20 11:33 UTC by sylvia0929

_Any italic text should be deleted from the final Pull Request text, including this line_

# Description

This commit updates the analytics component and related AngularJS module to improve functionality and maintain compatibility with the latest requirements. The changes involve:

Migrating the analytics component to a more modern structure, enhancing performance and maintainability.
Refactoring the AngularJS module to ensure smoother integration with other components and the overall architecture.
Addressing any deprecated features or outdated practices in the existing analytics module to align with the project's current best practices.

## Testing Checklist:

-Tested in latest Chrome
-Tested in latest Safari
-Tested in latest Firefox

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-09-22 13:35 UTC, AusBruce commented
I have test your code in my local machine, it runs well. before and after looks exactly the same. It is good to see you that you have make change in doubtfire.state.

2024-09-25 09:22 UTC, JackSCarroll commented
These changes successfully unlink references to analytics.coffee and recreates the route in doubtfire.states to utilise the existing unit-analytics-route component files.
The old analytics.coffee and analytics.tpl.html files should be deleted now that they aren't being used.
There may be a need to rename this branch because this isn't a migration task.

2024-10-14 11:38 UTC, aNebula commented on src/app/config/config.coffee
> +  #'doubtfire.config.analytics'
- [ ] Remove commented lines from code

2024-10-14 11:38 UTC, aNebula commented on src/app/doubtfire-angularjs.module.ts
> +//import 'build/src/app/config/analytics/analytics.js';
- [ ] Remove commented lines from code

2024-10-14 11:38 UTC, aNebula commented on src/app/doubtfire-angularjs.module.ts
> +//import 'build/src/app/units/states/analytics/analytics.js';
- [ ] Remove commented lines from code

2024-10-14 11:38 UTC, aNebula requested changes

2024-10-14 11:38 UTC, aNebula commented on src/app/units/states/states.coffee
> +  #'doubtfire.units.states.analytics'
- [ ] Remove commented lines from code

2024-10-14 11:45 UTC, aNebula commented
@sylvia0929 please remove the commented lines from code - comments should only be used to provide explanation or documentation of complex behaviour; comments should never be a replacement for deleting code.
After that, please open an upstream pull request against [9.x branch of doubtfire-lms/doubtfire-web](https://github.com/doubtfire-lms/doubtfire-web/tree/9.x) to add your changes to upstream and get credited for your contributions in your personal Github portfolio.

2024-10-14 11:45 UTC, closed without merging